### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by renich** [damex/funtoo-tengine#2]
Here goes... <gulp>...

Hey man, what's up? I was gonna suggest why not provide a systemd service unit along with the rest? This way, if a user enables systemd, she can start the service by using it.

Here's a working example (taken from nginx's service unit; from Gentoo):

```ini
[Unit]
Description=The tengine HTTP and reverse proxy server
After=network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/run/tengine.pid
ExecStartPre=/usr/sbin/tengine -t
ExecStart=/usr/sbin/tengine
ExecReload=/bin/kill -HUP $MAINPID
ExecStop=/bin/kill -QUIT $MAINPID

[Install]
WantedBy=multi-user.target
```

All that is needed is to install it with the `systemd_newunit` macro-thing-command.

How about it?

**Comment by damex** [comment]
glad to hear there is still some love for tengine and someone still use (or try to use) my overlay. sure, i will update ebuilds + include systemd unit.

**Comment by renich** [comment]
:D. I am creating a planet in ruby: https://GitHub.com/Renich/greg

The preferred server configuration is for tengine. ;)

Thank you; for your hard work. It is highly appreciated!

**Comment by damex** [comment]
renich@, i added systemd support for last tengine ebuild. please check if it works for you.

**Comment by renich** [comment]
Works fine, man. Thanks a lot @damex.

**Comment by damex** [comment]
sure, thank you. closing ticket/issue.
